/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 elephpant.glb -T 
Files: elephpant.glb [11.04MB] > C:\Users\USER\Documents\WEB PAHRI\ThreeJsPortofolio\public\models\elephpant-transformed.glb [525.52KB] (95%)
Author: Aleksey Nemiro (https://sketchfab.com/alekseynemiro)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/elephpant-c8dc1f9a7f2443c49a1c1fc9fb1b4542
Title: elePHPant
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/elephpant-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Body_0.geometry} material={materials.Body} position={[-0.807, 2.163, -0.482]} rotation={[-Math.PI / 2, 0, 0]} scale={0.799} />
      <mesh geometry={nodes.Body_1.geometry} material={materials.Feet} position={[-0.807, 2.163, -0.482]} rotation={[-Math.PI / 2, 0, 0]} scale={0.799} />
      <mesh geometry={nodes.php_0.geometry} material={materials.Text} position={[-0.032, 2.278, 0.175]} rotation={[0.183, Math.PI / 2, 0]} scale={0.58} />
    </group>
  )
}

useGLTF.preload('/elephpant-transformed.glb')
