/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 personal_computer.glb -T 
Files: personal_computer.glb [874.54KB] > C:\Users\USER\Documents\WEB PAHRI\ThreeJsPortofolio\public\models\personal_computer-transformed.glb [54.25KB] (94%)
Author: Juan Foo (https://sketchfab.com/juanotron)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/personal-computer-b943e06de72c4b2b9ac6b9d7ca813f8f
Title: Personal Computer
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function MailComputer(props) {
  const { nodes, materials } = useGLTF(
    "/models/personal_computer-transformed.glb"
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.monitor_gray_0.geometry}
        material={materials.gray}
        position={[-0.491, 15.204, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.183}
      />
      <mesh
        geometry={nodes.monitor_vintage_2_0.geometry}
        material={materials.vintage_2}
        position={[-0.491, 15.204, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.183}
      />
      <mesh
        geometry={nodes.monitor_white001_0.geometry}
        material={materials["white.001"]}
        position={[-0.491, 15.204, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.183}
      />
      <mesh
        geometry={nodes.monitor_screen_0.geometry}
        material={materials.screen}
        position={[-0.491, 15.204, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.183}
      />
      <mesh
        geometry={nodes.monitor_black_0.geometry}
        material={materials.black}
        position={[-0.491, 15.204, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.183}
      />
      <mesh
        geometry={nodes.cpu_white_0.geometry}
        material={materials.white}
        position={[-0.468, 14.846, -0.018]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.183}
      />
      <mesh
        geometry={nodes.cpu_gray_metallic_0.geometry}
        material={materials.gray_metallic}
        position={[-0.468, 14.846, -0.018]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.183}
      />
      <mesh
        geometry={nodes.cpu_metallic_0.geometry}
        material={materials.metallic}
        position={[-0.468, 14.846, -0.018]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.183}
      />
      <mesh
        geometry={nodes.cpu_green_0.geometry}
        material={materials.green}
        position={[-0.468, 14.846, -0.018]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.183}
      />
      <mesh
        geometry={nodes.cpu_gray_stiker_0.geometry}
        material={materials.gray_stiker}
        position={[-0.468, 14.846, -0.018]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.183}
      />
      <mesh
        geometry={nodes.flopy_vintage_1_0.geometry}
        material={materials.vintage_1}
        position={[-0.34, 14.847, -0.018]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.183}
      />
    </group>
  );
}

useGLTF.preload("/models/personal_computer-transformed.glb");

export default MailComputer;
