/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 game_ready_animated_mailbox__postbox.glb -T 
Files: game_ready_animated_mailbox__postbox.glb [652.03KB] > C:\Users\USER\Documents\WEB PAHRI\ThreeJsPortofolio\public\models\game_ready_animated_mailbox__postbox-transformed.glb [85.49KB] (87%)
Author: OmegaRedZA (https://sketchfab.com/OmegaRedZA)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/game-ready-animated-mailbox-postbox-582c0ce1ffee41179ab981146ae0ff87
Title: Game Ready Animated Mailbox / Postbox
*/

import React from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Mailbox(props) {
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTF(
    "/models/game_ready_animated_mailbox__postbox-transformed.glb"
  );
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Dummy001"
          position={[0.034, 0.942, -0.232]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.017}
        >
          <group
            name="Cylinder001"
            position={[6.625, -10.738, 9.669]}
            rotation={[1.716, 1.558, 2.996]}
            scale={0.866}
          >
            <mesh
              name="Cylinder001_07_-_Default_0"
              geometry={nodes["Cylinder001_07_-_Default_0"].geometry}
              material={materials["08_-_Default"]}
            />
            <mesh
              name="Cylinder001_03_-_Default_0"
              geometry={nodes["Cylinder001_03_-_Default_0"].geometry}
              material={materials["09_-_Default"]}
            />
            <mesh
              name="Cylinder001_02_-_Default_0"
              geometry={nodes["Cylinder001_02_-_Default_0"].geometry}
              material={materials["02_-_Default"]}
            />
            <mesh
              name="Cylinder001_01_-_Default_0"
              geometry={nodes["Cylinder001_01_-_Default_0"].geometry}
              material={materials["01_-_Default"]}
            />
          </group>
          <group
            name="Box002"
            position={[-2.728, -1.764, 0]}
            rotation={[0, 0, -Math.PI]}
          >
            <mesh
              name="Box002_01_-_Default_0"
              geometry={nodes["Box002_01_-_Default_0"].geometry}
              material={materials["01_-_Default"]}
            />
          </group>
        </group>
        <mesh
          name="Tube001_01_-_Default_0"
          geometry={nodes["Tube001_01_-_Default_0"].geometry}
          material={materials["01_-_Default"]}
          position={[-0.018, 1.105, -0.204]}
          rotation={[0.003, 0, 0]}
          scale={0.017}
        />
        <mesh
          name="Tube001_09_-_Default_0"
          geometry={nodes["Tube001_09_-_Default_0"].geometry}
          material={materials["09_-_Default"]}
          position={[-0.018, 1.105, -0.204]}
          rotation={[0.003, 0, 0]}
          scale={0.017}
        />
        <mesh
          name="Tube001_08_-_Default_0"
          geometry={nodes["Tube001_08_-_Default_0"].geometry}
          material={materials["08_-_Default"]}
          position={[-0.018, 1.105, -0.204]}
          rotation={[0.003, 0, 0]}
          scale={0.017}
        />
        <mesh
          name="Tube001_02_-_Default_0"
          geometry={nodes["Tube001_02_-_Default_0"].geometry}
          material={materials["02_-_Default"]}
          position={[-0.018, 1.105, -0.204]}
          rotation={[0.003, 0, 0]}
          scale={0.017}
        />
        <mesh
          name="Box006_15_-_Default_0"
          geometry={nodes["Box006_15_-_Default_0"].geometry}
          material={materials["15_-_Default"]}
          position={[0.015, 0.967, 0.006]}
          rotation={[-1.475, 0.711, 2.996]}
          scale={0.017}
        />
        <mesh
          name="Box003_13_-_Default_0"
          geometry={nodes["Box003_13_-_Default_0"].geometry}
          material={materials["13_-_Default"]}
          position={[-0.07, 0.954, 0.006]}
          rotation={[-Math.PI / 2, -0.716, 0]}
          scale={0.017}
        />
        <mesh
          name="Box004_14_-_Default_0"
          geometry={nodes["Box004_14_-_Default_0"].geometry}
          material={materials["14_-_Default"]}
          position={[0.117, 0.954, 0.03]}
          rotation={[-1.571, -1.553, 0]}
          scale={0.017}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/game_ready_animated_mailbox__postbox-transformed.glb");

export default Mailbox;
