/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 rocket.glb -T 
Files: rocket.glb [58.28MB] > C:\Users\USER\Documents\WEB PAHRI\ThreeJsPortofolio\public\models\rocket-transformed.glb [2.15MB] (96%)
Author: AyoubBani (https://sketchfab.com/AyoubBani)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rocket-b17a0f9f805c4fa7b978829006bbb57f
Title: Rocket
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Rocket(props) {
  const { nodes, materials } = useGLTF('/models/rocket-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder_white_0.geometry} material={materials.PaletteMaterial001} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/rocket-transformed.glb');
export default Rocket
